# Generated by Django 5.1.5 on 2025-01-29 22:31

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('orientation', models.CharField(max_length=1, verbose_name='orientation')),
                ('window_wall_ratio', models.FloatField(verbose_name='window_wall_ratio')),
                ('depth_of_shade', models.FloatField(verbose_name='depth_of_shade')),
                ('wall_r_value', models.FloatField(verbose_name='wall_R_value')),
                ('glass_U_factor', models.FloatField(verbose_name='glass_u_factor')),
                ('cooling', models.FloatField(blank=True, verbose_name='cooling')),
                ('heating', models.FloatField(blank=True, verbose_name='heating')),
                ('lighting', models.FloatField(blank=True, verbose_name='lighting')),
            ],
            options={
                'verbose_name_plural': 'data_inputs',
            },
        ),
    ]
